image: maven:latest

stages:
  - build
  - test

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn -verify
    - echo "Building"
    - mkdir build
    - touch build/info.txt
    - mvn clean compile -V -e -f solution/pom.xml
  artifacts:
    paths:
      - build/


test:
  stage: test
  script:
    - echo "report will be below here"
    - mvn verify -e -f solution/pom.xml
  artifacts:
    when: always
    paths:
      - /target/surefire-reports/TEST-*.xml
      - pomMain/target/failsafe-reports/TEST-*.xml
      - pomMain/target/surefire-reports/*.txt
      - pomMain/target/failsafe-reports/*.txt

