image: maven:latest

stages:
  - build
  - test


cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn -verify
    - echo "Building"
    - mkdir build
    - touch build/info.txt
    - mvn clean compile -V -e -f pomMain/pom.xml
  artifacts:
    paths:
      - build/


#test:
#  stage: test
#  script:
#    - mvn $MAVEN_CLI_OPTS test
