image: maven:latest

stages:
  - build
  - test

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn -verify
    - echo "Building"
    - mkdir build
    - touch build/info.txt
    - mvn clean compile -V -e -f solution/pom.xml
  artifacts:
    paths:
      - build/


test:
  stage: test
  script:
    - echo "Testing"
    - mvn test -f solution/pom.xml

