.TH "PDFZENSOR" "1" "0.815"
.SH NAME
PDF-Zensor - a command line tool to censor PDF files
.SH SYNOPSIS
.B pdf-zensor
[\fB\-m\fR | \fB\-u\fR] [\fB\-hqVv\fR] [\fB\-o\fR \fI"out"\fR] [\fB\-e\fR \fI"regex"\fR [\fI"hex_color"\fR]]... \fI"in.pdf"\fR
.SH DESCRIPTION
PDF-Zensor can be used to censor PDF-documents. As such it strips annotations and metadata aswell as textual and graphical content from the pdf file. It can also partially censor PDF files aswell as highlight certain text phrases. The individual colors for censoring different elements can be configured.
.SS OPTIONS
.TP
\fB\-e\fP, \fB\--expression\fP "regex" [\fI"hex_color"\fR]
.TP
\fB\-h\fP, \fB\--help\fP
Show this help message and exit.
.TP
\fB\-m\fP, \fB\--censor-marked\fP
Include only marked segments when censoring.
.TP
\fB\-o\fP, \fB\--out\fP "out"
The output file or path the censored file should be written to.
.TP
\fB\-q\fP, \fB\--quiet\fP
Silence the logging.
.TP
\fB\-u\fP, \fB\--censor-unmarked\fP
Exclude all marked segments when censoring.
.TP
\fB\-v\fP, \fB\--verbose\fP
Sets the loggers verbosity. Specify multiple \fB\-v\fP options to increase verbosity.
.TP
\fB\-V\fP, \fB\--version\fP
Print version information and exit.
.SS PARAMETERS
.TP
\fI"in.pdf"\fP
Set the input PDF-file that should be censored. Required.
.SH EXAMPLES
.TP
Censor the whole PDF-document:
pdf-zensor "in.pdf"
.TP
Censor the whole PDF-document and specify an output PDF-document:
pdf-zensor "in.pdf" -o "out.pdf"
.TP
Censor the marked parts of the PDF-document:
pdf-zensor -m "in.pdf"
.TP
Censor the unmarked parts of the PDF-document:
pdf-zensor -u "in.pdf"
